-- auto Generated on 2018-10-25 21:44:54 
-- DROP TABLE IF EXISTS `f_admin`; 
CREATE TABLE f_admin(
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id',
    `code` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'code',
    `username` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'username',
    `password` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'password',
    `name` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'name',
    `sex` BIGINT NOT NULL DEFAULT -1 COMMENT 'sex',
    `age` BIGINT NOT NULL DEFAULT -1 COMMENT 'age',
    `post` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'post',
    `qq` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'qq',
    `tel` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'tel',
    `email` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'email',
    `other` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'other',
    `role_id` BIGINT NOT NULL DEFAULT -1 COMMENT 'role_id',
    `state` BIGINT NOT NULL DEFAULT -1 COMMENT 'state',
    `add_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'add_time',
    `login_time` DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT 'login_time',
    `remark` VARCHAR(50) NOT NULL DEFAULT '' COMMENT 'remark',
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'f_admin';
